apiVersion: v2
appVersion: 3.1.9
description: The Log Shipping App forwards cluster logs to storage backends
home: https://github.com/giantswarm/fluent-logshipping-app
icon: https://s.giantswarm.io/app-icons/1/png/fluent-logshipping-app-light.png
name: fluent-logshipping-app
sources:
  - https://github.com/giantswarm/fluent-logshipping-app
version: 5.5.2
annotations:
  io.giantswarm.application.team: atlas
  io.giantswarm.application.audience: all
  io.giantswarm.application.managed: "true"
