apiVersion: v1
appVersion: 1.9.3
description: The Log Shipping App forwards cluster logs to storage backends
engine: gotpl
home: https://github.com/giantswarm/fluent-logshipping-app
icon: https://s.giantswarm.io/app-icons/1/png/fluent-logshipping-app-light.png
name: fluent-logshipping-app
sources:
- https://github.com/giantswarm/fluent-logshipping-app
version: [[ .Version ]]
annotations:
  application.giantswarm.io/team: team-atlas
  config.giantswarm.io/version: 1.x.x
